#!/bin/bash

pkgver=$1
pkgrel=$2

[[ $pkgver && $pkgrel ]] || exit 1

git clean -dfx

tag="$pkgver-$pkgrel"

sed -i \
    -e "s|^pkgver=.*|pkgver=$pkgver|" \
    -e "s|^pkgrel=.*|pkgrel=$pkgrel|" \
        PKGBUILD

md5sums=$(makepkg -g)
sed -i -e "s|^md5sums=.*|$md5sums|" PKGBUILD

makepkg -s
makepkg --source
