#!/bin/bash

pkgver=$1
pkgrel=$2

[[ $pkgver && $pkgrel ]] || exit 1

tag="$pkgver-$pkgrel"
md5sums=$(makepkg -g)

git clean -dfx

sed -i \
    -e "s|^pkgver=.*|pkgver=$pkgver|" \
    -e "s|^pkgrel=.*|pkgrel=$pkgrel|" \
    -e "s|^md5sums=.*|$md5sums|" \
        PKGBUILD

makepkg -s
makepkg --source
